[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/generate/prompt/*"
  to = "/.netlify/functions/generate"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
